name: Telegram Playlist Live

on:
  workflow_dispatch:
    inputs:
      playlist:
        description: "Masukkan URL video (pisahkan dengan spasi)"
        required: true

jobs:
  stream:
    runs-on: ubuntu-latest
    timeout-minutes: 360

    steps:
      - name: Install FFmpeg
        run: |
          sudo apt update
          sudo apt install -y ffmpeg

      - name: Start Playlist Streaming
        env:
          RTMP_URL: ${{ secrets.RTMP_URL }}
        run: |

          URLS="${{ github.event.inputs.playlist }}"

          echo "Playlist:"
          echo "$URLS"

          for video in $URLS
          do
            echo "=============================="
            echo "Now Streaming: $video"
            echo "=============================="

            ffmpeg -re \
            -fflags +genpts \
            -rw_timeout 15000000 \
            -i "$video" \
            -c:v libx264 \
            -preset veryfast \
            -b:v 1500k \
            -maxrate 1500k \
            -bufsize 3000k \
            -g 50 \
            -pix_fmt yuv420p \
            -c:a aac \
            -b:a 96k \
            -ar 44100 \
            -f flv "$RTMP_URL"

            echo "Video selesai atau error, lanjut ke berikutnya..."
          done

          echo "Playlist selesai."
