name: Telegram Playlist Live

on:
  workflow_dispatch:
    inputs:
      playlist:
        description: "Masukkan URL video dipisahkan spasi"
        required: true

jobs:
  stream:
    runs-on: ubuntu-latest

    steps:
      - name: Install FFmpeg
        run: |
          sudo apt update
          sudo apt install -y ffmpeg

      - name: Generate Playlist
        run: |
          echo "${{ github.event.inputs.playlist }}" | tr ' ' '\n' > raw_playlist.txt

          while read line; do
            echo "file '$line'" >> playlist.txt
          done < raw_playlist.txt

          echo "Playlist:"
          cat playlist.txt

      - name: Start Streaming
        env:
          RTMP_URL: ${{ secrets.RTMP_URL }}
        run: |

          ffmpeg -re \
          -protocol_whitelist "file,http,https,tcp,tls" \
          -f concat -safe 0 -i playlist.txt \
          -c:v libx264 \
          -preset veryfast \
          -b:v 3000k \
          -maxrate 3000k \
          -bufsize 6000k \
          -pix_fmt yuv420p \
          -c:a aac \
          -b:a 128k \
          -ar 44100 \
          -f flv "$RTMP_URL"
